### ISSUE TITLE
在mac 上出现崩溃

### ISSUE THREAD

**Issue by AndyZhangHong** [fumiama/maple-diffusion-naifu#1]
机型：MacBook Pro
芯片：m1 pro
内存：16g
增加分辨率就崩溃
<img width="512" alt="image" src="https://user-images.githubusercontent.com/28505806/203323927-4fa47829-a680-4fe2-9862-7a21d4de3416.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/28505806/203323978-3cc71e4c-cc3b-4b7f-975c-c0ffba64fbea.png">

**Comment by fumiama** [comment]
正常现象。这是因为🍎的mps的大内存分配有问题，在🍎解决这一问题之前，没有什么好办法。

p.s. 如果有找到临时的解决办法，欢迎PR！
